const messages = [["day", "JEUDI 10 OCTOBRE", null, null], ["them", "Vi, tu peux me rejoindre ce soir ?", "20:13"], ["me", "Oui, où ça ?", "20:15"], ["them", "Chez moi ? Ou même juste dehors, comme tu veux.", "20:16"], ["me", "Tu m'inquiètes 😭", "20:16"], ["them", "J'ai un truc important à te dire.", "20:17"], ["me", "Maintenant tu vas évidemment pas me laisser tranquille jusqu'à ce que tu me dises.", "20:18"], ["them", "Non 😂 mais viens. J'ai besoin de te le dire en face.", "20:19"], ["day", "VENDREDI 11 OCTOBRE", null, null], ["me", "Bon. J'ai attendu toute la journée. Tu me racontes ?", "18:42"], ["them", "Pas par messages. Promis je te dirai.", "18:50"], ["me", "Serena, tu sais que tu peux tout me dire hein.", "18:51"], ["them", "Je sais ❤️", "18:52"], ["day", "DIMANCHE 13 OCTOBRE", null, null], ["them", "Tu fais quoi cette semaine ?", "11:07"], ["me", "Lundi danse, mardi rien, mercredi je bosse. Pourquoi ?", "11:12"], ["them", "Parce que j'aimerais vraiment qu'on se voie.", "11:14"], ["me", "Tu me stresses de plus en plus 😂", "11:15"], ["them", "Je sais. Mais j'arrive pas à le dire correctement.", "11:17"], ["me", "Commence juste par le début.", "11:18"], ["them", "D'accord.", "11:20"], ["them", "Je ne t'ai pas tout dit la première fois.", "11:21"], ["me", "A propos de quoi ?", "11:21"], ["them", "D'Asher.", "11:22"], ["me", "Je t'écoute.", "11:22"], ["them", "Je t'avais dit que j'avais fait une connerie. Mais c'est plus compliqué que ça.", "11:24"], ["me", "Serena…", "11:24"], ["them", "J'ai trompé Asher.", "11:25"], ["me", "Je me doutais que c'était ça.", "11:26"], ["them", "Pas juste une fois et pas juste un truc sans importance.", "11:27"], ["me", "Avec qui ?", "11:27"], ["them", "Avec quelqu'un que je voyais depuis un moment.", "11:29"], ["me", "Attends… tu avais une relation cachée ?", "11:29"], ["them", "Oui.", "11:30"], ["me", "Et Asher n'est au courant de rien ?", "11:30"], ["them", "Non.", "11:31"], ["me", "Et tu me dis ça maintenant parce que… ?", "11:32"], ["them", "Parce que je viens d'apprendre que je suis enceinte.", "11:33"], ["me", "Serena 😳", "11:33"], ["them", "Et je ne sais pas qui est le père.", "11:34"], ["me", "… c'est lui ?", "11:34"], ["them", "Je ne sais pas.", "11:35"], ["me", "Mais tu sais qui c'est.", "11:35"], ["them", "Oui.", "11:36"], ["me", "Alors dis-moi.", "11:36"], ["them", "Non.", "11:37"], ["me", "Pourquoi ?", "11:37"], ["them", "Parce que je ne veux pas que son nom sorte de cette conversation.", "11:38"], ["me", "Tu peux me faire confiance.", "11:39"], ["them", "Je sais. Mais ce n'est pas seulement mon secret.", "11:40"], ["me", "Tu es en train de me dire que je le connais ?", "11:40"], ["them", "Peut-être.", "11:41"], ["me", "Serena…", "11:41"], ["them", "Je n'ai jamais dit qu'il ne serait pas là à Halloween.", "11:42"], ["me", "Attends quoi ? 😳", "11:43"], ["them", "Je dois arrêter d'en parler.", "11:43"], ["me", "Je vais devenir folle.", "11:44"], ["them", "Je sais. Désolée ❤️", "11:44"]];
const chat=document.getElementById("chat");
function esc(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
for(const m of messages){
  if(m[0]==="day"){const d=document.createElement("div");d.className="day";d.textContent=m[1];chat.appendChild(d);continue;}
  const row=document.createElement("div");row.className="row "+m[0];
  row.innerHTML='<div><div class="bubble">'+esc(m[1])+'</div><div class="meta">'+m[2]+'</div></div>';
  chat.appendChild(row);
}
window.scrollTo(0,document.body.scrollHeight);
document.getElementById("backBtn").onclick=()=>history.back();
